# -*- coding: utf-8 -*-
"""Modul perkalian.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dsBTDxkyp9EAHaGJCrKZQd7m7G-L3yBN
"""

def penjumlahan(angka1, angka2):
  jumlah = angka1 + angka2
  return jumlah